[PSN-305] Index custom attributes on Update on save
doofinder/doofinder-magento-101 pull request #12
Opened 2022-04-22 15:11 UTC by pedromcp90

2022-04-25 16:06 UTC, Aitor-Corrales requested changes

2022-04-25 16:06 UTC, Aitor-Corrales commented on Helper/StoreConfig.php
> +    public function getCustomAttributes(?int $storeId = null)
[Suggestion] Declare explicitly the return type in every function as you did in previous functions

2022-04-25 16:06 UTC, Aitor-Corrales commented on Model/Config/Indexer/Attributes.php
> +            if ($attribute['enabled'] === true) {
Why is explicitly conditioned against "true"?

2022-04-25 16:06 UTC, Aitor-Corrales commented on Model/Generator/Map/Product.php
> +        if ($product->getTypeId() == ProductType::TYPE_SIMPLE
`return ($product->getTypeId() == ProductType::TYPE_SIMPLE 
            && count($this->productTypeConfigurable->getParentIdsByChild($product->getId())) == 0)`

2022-04-26 09:37 UTC, pedromcp90 commented on Model/Config/Indexer/Attributes.php
> +            if ($attribute['enabled'] === true) {
Because the expected value is true

2022-04-26 09:45 UTC, pedromcp90 commented on Helper/Product.php
> +    public function getAttributeArray(ProductModel $product, string $attributeCode): ?array
I've created a method that obtains the attribute

2022-04-26 10:43 UTC, pedromcp90 commented on Model/Generator/Map/Product.php
> +        if ($product->getTypeId() == ProductType::TYPE_SIMPLE
Done, thanks

2022-04-26 14:34 UTC, sofia-doofinder approved these changes

2022-04-26 14:36 UTC, Aitor-Corrales commented on Model/Config/Indexer/Attributes.php
> +            if ($attribute['enabled'] === true) {
Wouldn't it be the same as `if ($attribute['enabled']) {` ?

2022-04-26 14:37 UTC, Aitor-Corrales approved these changes

2022-04-26 15:11 UTC, pedromcp90 commented on Model/Config/Indexer/Attributes.php
> +            if ($attribute['enabled'] === true) {
It wouldn't be the same because if the given value is a string it would be true, so I prefer to check its value explicitly

2022-05-03 10:32 UTC, merged