Added creation in update_on_save
doofinder/doofinder-magento-101 pull request #6
Opened 2022-03-17 10:17 UTC by sofia-doofinder

- When a new item (with visibility visible) is created in magento the update_on_save index it in doofinder.
- Modified the fields that are send to doofinder in the updated_on_save to adjust it to the indexation process.

2022-03-17 10:47 UTC, alvanieto approved these changes

2022-03-18 09:06 UTC, Aitor-Corrales requested changes

2022-03-18 09:06 UTC, Aitor-Corrales commented on Cron/Processor.php
> +                    $collection = $this->changedProductCollectionFactory->create()->filterCreated((int)$store->getId());
could we get this 3 blocks into separate functions?

2022-03-18 09:06 UTC, Aitor-Corrales commented on Model/Generator/Map/Product.php
> +    {
Should this return a nullable response or just a string with empty value if it does not fit the conditions?

2022-03-18 09:06 UTC, Aitor-Corrales commented on Model/ProductRepository.php
> +        $websiteId = $this->storeConfig->getCurrentStore()->getWebsiteId();
Does this work correctly in every store even without the environment emulation then?

2022-03-18 09:06 UTC, Aitor-Corrales commented on Observer/AbstractChangedProductObserver.php
> +                if ($product->getUpdatedAt() == $product->getCreatedAt()
Repair indentation and format please

2022-03-18 12:10 UTC, sofia-doofinder commented on Model/ProductRepository.php
> +        $websiteId = $this->storeConfig->getCurrentStore()->getWebsiteId();
I think it is working correctly bug I've added the emulation again because it maybe breaks something that I haven't realized...

2022-03-18 14:20 UTC, Aitor-Corrales approved these changes

2022-03-21 09:07 UTC, merged